### ISSUE TITLE
Are  cut/copy/paste events considered to be user initiated in the new API?

### ISSUE THREAD

**Issue by gked** [garykac/clipboard#4]
I have a question about the text below. Does this mean that we can no longer consider cut/copy/paste events as user initiated events then?

"Make it easier to support alternate permission models. 
For example, to enable web apps to copy to the clipboard without requiring a user gesture.
..."

**Comment by garykac** [comment]
Yes, I believe that it doesn't make sense to always associate cut/copy/paste operations with user-initiated events. It's not a good assumption now in any case (since IE does not restrict to user gestures).

Also, the user gesture requirement feels like a workaround for the real problem of wanting to prevent drive-by clipboard access. IE addressed this problem via a permission prompt (which has UX problems), while other browsers opted for the user gesture requirement (which is not perfect).

User gesture is not a great indication of user granting access to clipboard, and it's easily abused (e.g., click on button that says it will do one thing, but it (silently) does something else with the clipboard).

Ideally, I think the Permissions API is a good way of addressing this problem, but the spec would probably need to be flexible enough to allow browsers to decide how to grant permission (unless everyone agrees on a particular approach).
